version: '3'

services:
  db:
    image : mongo
    environment:
      MONGO_INITDB_DATABASE: db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
